curl http://node00.ddns.net:8888/lect/db/elements/xenon.txt > xenon.txt
curl http://node00.ddns.net:8888/lect/db/elements/aluminium.txt > aluminium.txt
curl http://node00.ddns.net:8888/lect/db/elements/argon.txt > argon.txt
curl http://node00.ddns.net:8888/lect/db/elements/barium.txt > barium.txt
curl http://node00.ddns.net:8888/lect/db/elements/calcium.txt > calcium.txt
curl http://node00.ddns.net:8888/lect/db/elements/carbon.txt > carbon.txt
curl http://node00.ddns.net:8888/lect/db/elements/helium.txt > helium.txt
curl http://node00.ddns.net:8888/lect/db/elements/hydrogen.txt > hydrogen.txt
curl http://node00.ddns.net:8888/lect/db/elements/iron.txt > iron.txt
curl http://node00.ddns.net:8888/lect/db/elements/krypton.txt > krypton.txt
curl http://node00.ddns.net:8888/lect/db/elements/lithium.txt > lithium.txt
curl http://node00.ddns.net:8888/lect/db/elements/magnesium.txt > magnesium.txt
curl http://node00.ddns.net:8888/lect/db/elements/mercury.txt > mercury.txt
curl http://node00.ddns.net:8888/lect/db/elements/neon.txt > neon.txt
curl http://node00.ddns.net:8888/lect/db/elements/nitrogen.txt > nitrogen.txt
curl http://node00.ddns.net:8888/lect/db/elements/oxygen.txt > oxygen.txt
curl http://node00.ddns.net:8888/lect/db/elements/potassium.txt > potassium.txt
curl http://node00.ddns.net:8888/lect/db/elements/silicon.txt > silicon.txt
curl http://node00.ddns.net:8888/lect/db/elements/sodium.txt > sodium.txt
curl http://node00.ddns.net:8888/lect/db/elements/strontium.txt > strontium.txt
curl http://node00.ddns.net:8888/lect/db/elements/sulfur.txt > sulfur.txt
